"""add active field to users

Revision ID: a83fb4642aa4
Revises: dc3a9388bfb4
Create Date: 2024-06-07 17:46:49.240288

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a83fb4642aa4"
down_revision: Union[str, None] = "dc3a9388bfb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "active")
    # ### end Alembic commands ###
