"""remove subtask as entity

Revision ID: 4441f40e4a4e
Revises: 7d910055c1ce
Create Date: 2024-07-11 17:23:55.847868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4441f40e4a4e"
down_revision: Union[str, None] = "7d910055c1ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subtasks")
    op.add_column("tasks", sa.Column("parent_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_tasks_parent_id_tasks"), "tasks", "tasks", ["parent_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_tasks_parent_id_tasks"), "tasks", type_="foreignkey")
    op.drop_column("tasks", "parent_id")
    op.create_table(
        "subtasks",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("body", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("completed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("task_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name="fk_subtasks_task_id_tasks",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_subtasks_user_id_users"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_subtasks"),
    )
    # ### end Alembic commands ###
