"""add users realationships

Revision ID: 7d910055c1ce
Revises: 6a9f775bd8a3
Create Date: 2024-06-10 19:49:47.487120

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d910055c1ce"
down_revision: Union[str, None] = "6a9f775bd8a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subtasks", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        op.f("fk_subtasks_user_id_users"), "subtasks", "users", ["user_id"], ["id"]
    )
    op.add_column("tasks", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        op.f("fk_tasks_user_id_users"), "tasks", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_tasks_user_id_users"), "tasks", type_="foreignkey")
    op.drop_column("tasks", "user_id")
    op.drop_constraint(
        op.f("fk_subtasks_user_id_users"), "subtasks", type_="foreignkey"
    )
    op.drop_column("subtasks", "user_id")
    # ### end Alembic commands ###
