"""add email uq constraint

Revision ID: 6a9f775bd8a3
Revises: a83fb4642aa4
Create Date: 2024-06-07 19:50:04.182292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a9f775bd8a3"
down_revision: Union[str, None] = "a83fb4642aa4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_users_email"), "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    # ### end Alembic commands ###
